### PR TITLE
Update for JLab 3.0

### PR DESCRIPTION
**Pull request by isabela-pf**
Based on [jupyterlab #8038](https://github.com/jupyterlab/jupyterlab/issues/8038), this updates base JupyterLab from 2.0 and up to 3.0 and up. This is a user-facing change.

I am not well-versed in this repo, so please let me know if there is anything I am missing or anything that needs to be changed. Thanks in advance to whoever reviews this PR!

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @isabela-pf, looks good!

I opened https://github.com/jupyterlab/mimerender-cookiecutter-ts/pull/22 to fix the CI and to switch to GitHub Actions (just like for the other cookiecutters).

**Comment by blink1073** [comment]
Kicking to try and get GH actions to run.

**Comment by jtpio** [comment]
We'll need to update to JupyterLab 3 here:

https://github.com/jupyterlab/mimerender-cookiecutter-ts/blob/d6044053c5213a79bcb226a26bfa466e2c786784/.github/workflows/build.yml#L49

**Comment by jtpio** [comment]
@isabela-pf I don't seem to have push rights on this repo to do the inline change, so just opened this PR with your commit to update to JupyterLab 3.0 and fix the CI: #23 

We could then merge it and rebase #20 to switch to the new distribution system.

**Pull request closed without merging**
